-- NODE table
CREATE TABLE NODE (
	NODE_ID SERIAL PRIMARY KEY,
	CENTER BOOLEAN NOT NULL,
	COORDINATES POINT NOT NULL
);

-- EDGE table
CREATE TABLE EDGE (
	EDGE_ID VARCHAR PRIMARY KEY,
	SPEED FLOAT,
	ORIGIN INTEGER REFERENCES NODE(NODE_ID),
	DESTINATION INTEGER REFERENCES NODE(NODE_ID)
);

-- HISTORIC_DATA table
CREATE TABLE HISTORIC_DATA (
	ENTRY SERIAL PRIMARY KEY,
	NODE_ID INTEGER REFERENCES NODE(NODE_ID),
	WEIGHT FLOAT,
	DATE TIMESTAMP
);

-- ESTIMATED_DATA TABLE
CREATE TABLE ESTIMATED_DATA (
	NODE_ID INTEGER PRIMARY KEY REFERENCES NODE(NODE_ID),
	WEIGHT FLOAT
);

-- PENDING_ROUTES TABLE
CREATE TABLE PENDING_ROUTES (
	ID SERIAL PRIMARY KEY,
	TRUCK_ID INTEGER NOT NULL,
	ROUTE JSONB NOT NULL,
	CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
