"""Runner code to use graphs and path-finders."""

import os
from model import Graph
from algorithms import Algorithms


def run():
    """An example of using the model & algorithms modules.
    
    In this example a graph is created from a file, divided in zones & 
    subgraphs and paths are calculated for each subgraph. A path is also
    calculated for the initial graph using both TSP and VSP.
    """
    g = Graph()
    g.populate_from_file(os.getcwd() + "/files/test2.txt")
    #g.populate_from_file(os.getcwd() + "/Algorithm/AlgoCode/files/test2.txt")
    algo = Algorithms(g)
    """p, v = algo.run_ga_tsp(ngen=g.nodes * 100,
                           dir=os.getcwd() + "/plots",
                           name="_GA",
                           vrb=False)
    print(f"Total value (GA): {v}")"""
    p2, v2 = algo.run_two_opt(dir=os.getcwd() + "/plots", name="_2opt")
    print(f"Total value (2opt): {v2}")
    p3, v3 = algo.run_sa(dir=os.getcwd() + "/plots", name="_SA")
    print(f"Total value (SA): {v3}")
    p4, v4 = algo.run_tabu_search(dir=os.getcwd() + "/plots", name="_TS")
    print(f"Total value (TS): {v4}")
    res = g.divide_graph(725)
    print(f"Zone count (TSP): {len(res)}")
    sg = []
    for i, z in enumerate(res):
        sg.append(g.create_subgraph(z))
    t = 0
    for i, graph in enumerate(sg):
        algo2 = Algorithms(graph)
        p, v = algo2.run_ga_tsp(name=i + 1,
                                vrb=False,
                                dir=os.getcwd() + "/plots/GA")
        t += v
    print(f"Total value (GA zoned): {t}")
    t = 0
    for i, graph in enumerate(sg):
        algo2 = Algorithms(graph)
        p, v = algo2.run_two_opt(name=i + 1,
                                dir=os.getcwd() + "/plots/2opt")
        t += v
    print(f"Total value (2opt zoned): {t}")
    t = 0
    for i, graph in enumerate(sg):
        algo2 = Algorithms(graph)
        p, v = algo2.run_sa(name=i + 1,
                                dir=os.getcwd() + "/plots/SA")
        t += v
    print(f"Total value (SA zoned): {t}")
    t = 0
    for i, graph in enumerate(sg):
        algo2 = Algorithms(graph)
        p, v = algo2.run_tabu_search(name=i + 1,
                                dir=os.getcwd() + "/plots/TS")
        t += v
    print(f"Total value (TS zoned): {t}")


def run2():
    """Tests the TSP GA on the N files generated by `create2ton.py`"""
    for i in range(2, 75):
        print("----------------------------------------------------------")
        print(f"Graph{i}")
        g = Graph()
        g.populate_from_file(f"{os.getcwd()}/files/test2tonnodes/{i}n.txt")
        algo = Algorithms(g)
        _, v = algo.run_ga_tsp(dir=os.getcwd() + "/plots", idx=i, vrb=False)


def run3():
    g = Graph()
    g.populate_from_file(os.getcwd() + "/files/test2.txt")
    algo = Algorithms(g)
    a, b = algo.held_karp_lb(0)
    print(f"{a} - {b}")
    a, b = algo.one_tree(0)
    print(f"{a} - {b}")


def main():
    run3()


if __name__ == '__main__':
    main()
