"""Runner code to use graphs and path-finders."""

import os
from model import Graph
from algorithms import Algorithms


def run():
    """An example of using the model & algorithms modules.
    
    In this example a graph is created from a file, divided in zones & 
    subgraphs and paths are calculated for each subgraph. A path is also
    calculated for the initial graph using both TSP and VSP.
    """
    g = Graph()
    print("Loading graph")
    g.populate_from_file(os.getcwd() + "/files/test2.txt")
    #g.populate_from_file(os.getcwd() + "/Algorithm/AlgoCode/files/test2.txt")
    print("Graph loaded")
    algo = Algorithms(g)
    _, v = algo.run_ga_tsp(ngen=g.nodes * 100,
                           dir=os.getcwd() + "/plots",
                           vrb=True)
    print(f"Total value (TSP): {v}")
    """res = g.divide_graph(725)
    print(f"Zone count (TSP): {len(res)}")
    sg = []
    for i, z in enumerate(res):
        sg.append(g.create_subgraph(z))
    t = 0
    for i, graph in enumerate(sg):
        algo2 = Algorithms(graph)
        p, v = algo2.run_ga_tsp(idx=i + 1,
                                vrb=False,
                                dir=os.getcwd() + "/plots")
        print(p)
        t += v
    print(f"Total value (TSP zoned): {t}")"""


def run2():
    """Tests the TSP GA on the N files generated by `create2ton.py`"""
    for i in range(2, 75):
        print("----------------------------------------------------------")
        print(f"Graph{i}")
        g = Graph()
        g.populate_from_file(f"{os.getcwd()}/files/test2tonnodes/{i}n.txt")
        algo = Algorithms(g)
        _, v = algo.run_ga_tsp(dir=os.getcwd() + "/plots", idx=i, vrb=False)


def run3():
    g = Graph()
    print("Loading graph")
    g.populate_from_file(os.getcwd() + "/files/test2.txt")
    print("Graph loaded")
    algo = Algorithms(g)
    path = [0, 12, 9, 1, 6, 5, 2, 8, 7, 4, 3, 10]
    print(f"Fitness b4: {algo.evaluate(path)}")
    path2 = algo.optimization(path)
    print(f"Fitness after: {algo.evaluate(path2)}")


def main():
    run()


if __name__ == '__main__':
    main()
